version: '3'

services:

  db:
    build:
      context: ./requirements/mariadb/
    image: mariadb
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    build:
      context: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WP_URL=https://${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - app-network

  webserver:
    build:
      context: ./requirements/nginx/
    image: nginx
    extra_hosts:
      - "daprovin.42.fr:127.0.0.1"
    container_name: webserver
    restart: unless-stopped
    ports:
      - "443:443"
    env_file: .env
    environment:
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - app-network

volumes:
    wordpress:
      driver: local
      driver_opts:
        type: none
        device: ${WP_HOST_VOLUME_PATH}
        o: bind
    dbdata:
      driver: local
      driver_opts:
        type: none
        device: ${MARIADB_HOST_VOLUME_PATH}
        o: bind

networks:
    app-network:
      external:
        name: inception_network
